[project]
name = "zimbabwe_payroll"
version = "0.0.1"
description = "Zimbabwe payroll statutory calculations and reports for ERPNext"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "frappe",
    "erpnext"
]
authors = [
    {name = "CyteERP Systems", email = "support@cyteerp.com"}
]

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.bench]
app = "zimbabwe_payroll"

[tool.bench.frappe-dependencies]
frappe = "~15.0.0"
erpnext = "~15.0.0"
